api_key: livekit server api key. LIVEKIT_API_KEY env can be used instead
api_secret: livekit server api secret. LIVEKIT_API_SECRET env can be used instead
ws_url: livekit server websocket url. LIVEKIT_WS_URL can be used instead
redis:
  address: 172.17.0.1:6379

logging:
  level: info
storage:
  gcp:
    bucket: demo_voice_ai