services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./frontend/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env

  egress:
    image: livekit/egress:latest
    environment:
      - EGRESS_CONFIG_FILE=/out/config.yaml
    volumes:
      - ~/egress:/out

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"