services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    env_file:
      - ./frontend/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env
    depends_on:
      - postgres

  egress:
    image: livekit/egress:latest
    environment:
      - EGRESS_CONFIG_FILE=/out/config.yaml
    volumes:
      - ./egress:/out

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=optimind
      - POSTGRES_USER=optimind
      - POSTGRES_PASSWORD=optimind
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: