from .exam import MER_AGENT_PROMPT
from .reminder import MAX_REMINDER_AGENT_PROMPT, REMINDER_AGENT_PROMPT
from .feedback import INSURANCE_FEEDBACK_AGENT_PROMPT
from .appointment import MAX_MEDICAL_APPOINTMENT_PROMPT, MEDICAL_APPOINTMENT_PROMPT

SESSION_INSTRUCTIONS = """
Open the conversation naturally by introducing yourself.
"""

__all__ = [
    "MER_AGENT_PROMPT",
    "MAX_REMINDER_AGENT_PROMPT",
    "REMINDER_AGENT_PROMPT",
    "INSURANCE_FEEDBACK_AGENT_PROMPT",
    "MAX_MEDICAL_APPOINTMENT_PROMPT",
    "MEDICAL_APPOINTMENT_PROMPT",
    "SESSION_INSTRUCTIONS",
]
